from typing import Protocol

from app.application.entities.refresh_token import RefreshTokenRecord


class RefreshTokenRepository(Protocol):
    async def save(self, token_record: RefreshTokenRecord) -> None: ...

    async def get_by_jti(self, jti: str) -> RefreshTokenRecord | None: ...

    async def revoke(self, jti: str, reason: str | None = None) -> RefreshTokenRecord | None: ...

    async def revoke_subject_tokens(self, sub: str, reason: str | None = None) -> None: ...

    async def mark_compromised(self, jti: str, reason: str | None = None) -> RefreshTokenRecord | None: ...
