server {
    listen 80;
    server_name seu-dominio.com www.seu-dominio.com;

    # Local destinado aos arquivso mágicos do Certbot necessários para checagem e emissão do SSL
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Intercepta e Força qualquer tráfego desprotegido direto para HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name seu-dominio.com www.seu-dominio.com;

    # Certificados que serão injetados pelo Certbot no volume (Substitua na nuvem pelo seu domínio exato)
    ssl_certificate /etc/letsencrypt/live/seu-dominio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seu-dominio.com/privkey.pem;
    
    # Práticas Refinadas TLS v1.2+ e Cifra Sugerida via OWASP Cheat-Sheets
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";

    # Enforçamento Severo de Segurança no Nível Reverser-Proxy (Independente do FastAPI)
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
